OMNeT++ Simulation Library: Simulation Core
Simulation Core
Description
Classes in this group, such as cSimpleModule or cMessage, are essential to writing OMNeT++ simulation models.
cModule and cSimpleModule represent modules in the simulation. The user implements new modules by subclassing cSimpleModule and overriding its handleMessage() or activity() member function.
cChannel and subclasses encapsulate properties of connections between modules
cMessage represents events, and also messages sent among modules
cPar represents parameters of modules and channels
cGate represents module gates (attachment points of connections)
Classes
class cChannel
Base class for channels.
class cIdealChannel
Channel with zero propagation delay, zero transmission delay (infinite datarate), and always enabled.
class cComponent
Common base for module and channel classes.
class cDatarateChannel
Channel that models delay, bit error rate and data rate.
class cDelayChannel
Channel with propagation delay.
class cGate
Represents a module gate.
class cMessage
The message class in OMNeT++. cMessage objects may represent events, messages, jobs or other entities in a simulation. To represent network packets, use the cPacket subclass.
class cModule
This class represents modules in the simulation.
class cPacket
A subclass of cMessage to represent packets, frames, datagrams, application messages, and similar data.
class cPar
Represents a module or channel parameter.
class cSimpleModule
Base class for all simple module classes.
Functions
simtime_t simTime ()
Returns the current simulation time.
Function Documentation
simTime()
simtime_t omnetpp::simTime () inline
Returns the current simulation time.
References cSimulation::getActiveSimulation(), and cSimulation::getSimTime().
Referenced by cDatarateChannel::isBusy().