OMNeT++ Simulation Library: cLongHistogram Class Reference
cLongHistogram Class Reference
Statistical Result Collection
#include <clegacyhistogram.h>
Description
Equidistant histogram for integers.
DEPRECATED CLASS, use cHistogram instead.
This class is just a cLegacyHistogram preconfigured for collecting integers, that is, it operates in INTEGERS mode.
Public Member Functions
Constructors, destructor, assignment.
cLongHistogram (const cLongHistogram &r)
cLongHistogram (const char *name=nullptr, int numcells=-1, bool weighted=false)
virtual ~cLongHistogram ()
cLongHistogram & operator= (const cLongHistogram &other)
Redefined cObject member functions.
virtual cLongHistogram * dup () const override
Redefined member functions from cStatistic and its subclasses.
virtual void collect (double value) override
virtual void collect (SimTime value) override
Public Member Functions inherited from cLegacyHistogram
cLegacyHistogram (const cLegacyHistogram &r)
cLegacyHistogram (const char *name=nullptr, int numcells=-1, Mode mode=MODE_AUTO, bool weighted=false)
cLegacyHistogram & operator= (const cLegacyHistogram &res)
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual double getBinEdge (int k) const override
virtual double getBinValue (int k) const override
virtual double getPDF (double x) const override
virtual double getCDF (double x) const override
virtual double draw () const override
virtual void saveToFile (FILE *) const override
virtual void loadFromFile (FILE *) override
virtual void setMode (Mode mode)
virtual Mode getMode () const
virtual void setCellSize (double d)
virtual double getCellSize () const
Public Member Functions inherited from cLegacyHistogramBase
cLegacyHistogramBase (const cLegacyHistogramBase &r)
cLegacyHistogramBase (const char *name, int numcells, bool weighted=false)
virtual ~cLegacyHistogramBase ()
cLegacyHistogramBase & operator= (const cLegacyHistogramBase &res)
virtual void clear () override
virtual void setUpBins () override
virtual int getNumBins () const override
virtual void setNumCells (int numcells)
Public Member Functions inherited from cPrecollectionBasedDensityEst
cPrecollectionBasedDensityEst (const cPrecollectionBasedDensityEst &other)
cPrecollectionBasedDensityEst (const char *name=nullptr, bool weighted=false)
virtual ~cPrecollectionBasedDensityEst ()
cPrecollectionBasedDensityEst & operator= (const cPrecollectionBasedDensityEst &res)
virtual void collectWeighted (double value, double weight) override
virtual void merge (const cStatistic *other) override
virtual void setRange (double lower, double upper)
virtual void setRangeAuto (int numPrecollect=100, double rangeExtensionFactor=2.0)
virtual void setRangeAutoLower (double upper, int numPrecollect=100, double rangeExtensionFactor=2.0)
virtual void setRangeAutoUpper (double lower, int numPrecollect=100, double rangeExtensionFactor=2.0)
virtual void setNumPrecollectedValues (int numPrecollect)
virtual int getNumPrecollectedValues () const
virtual double getRangeExtensionFactor () const
virtual bool binsAlreadySetUp () const override
virtual int64_t getNumUnderflows () const override
virtual int64_t getNumOverflows () const override
virtual double getUnderflowSumWeights () const override
virtual double getOverflowSumWeights () const override
virtual int64_t getNumNegInfs () const override
virtual int64_t getNumPosInfs () const override
virtual double getNegInfSumWeights () const override
virtual double getPosInfSumWeights () const override
Public Member Functions inherited from cAbstractHistogram
cAbstractHistogram (const cAbstractHistogram &other)
cAbstractHistogram (const char *name=nullptr, bool weighted=false)
virtual ~cAbstractHistogram ()
cAbstractHistogram & operator= (const cAbstractHistogram &res)
virtual double getBinPDF (int k) const
virtual Bin getBinInfo (int k) const
virtual _OPPDEPRECATED bool isTransformed () const final
virtual _OPPDEPRECATED void transform () final
virtual _OPPDEPRECATED int getNumCells () const final
virtual _OPPDEPRECATED double getBasepoint (int k) const final
virtual _OPPDEPRECATED double getCellValue (int k) const final
virtual _OPPDEPRECATED double getCellPDF (int k) const final
virtual _OPPDEPRECATED int64_t getUnderflowCell () const final
virtual _OPPDEPRECATED int64_t getOverflowCell () const final
virtual _OPPDEPRECATED Bin getCellInfo (int k) const final
Public Member Functions inherited from cStdDev
cStdDev (const cStdDev &r)
cStdDev (const char *name=nullptr, bool weighted=false)
virtual ~cStdDev ()
cStdDev & operator= (const cStdDev &res)
virtual std::string str () const override
virtual bool isWeighted () const override
virtual int64_t getCount () const override
virtual double getSum () const override
virtual double getSqrSum () const override
virtual double getMin () const override
virtual double getMax () const override
virtual double getMean () const override
virtual double getStddev () const override
virtual double getVariance () const override
virtual double getSumWeights () const override
virtual double getWeightedSum () const override
virtual double getSqrSumWeights () const override
virtual double getWeightedSqrSum () const override
Public Member Functions inherited from cStatistic
cStatistic (const cStatistic &r)
cStatistic (const char *name=nullptr)
virtual ~cStatistic ()
cStatistic & operator= (const cStatistic &res)
virtual void collectWeighted (SimTime value, double weight)
virtual void collectWeighted (double value, SimTime weight)
virtual void collectWeighted (SimTime value, SimTime weight)
virtual void record ()
virtual void recordWithUnit (const char *unit)
virtual void recordAs (const char *name, const char *unit=nullptr)
virtual _OPPDEPRECATED double getWeights () const final
virtual _OPPDEPRECATED void collect2 (double value, double weight) final
virtual _OPPDEPRECATED void collect2 (SimTime value, double weight) final
virtual _OPPDEPRECATED void collect2 (double value, SimTime weight) final
virtual _OPPDEPRECATED void collect2 (SimTime value, SimTime weight) final
virtual _OPPDEPRECATED double random () const final
virtual _OPPDEPRECATED void clearResult () final
Public Member Functions inherited from cRandom
cRandom (cRNG *rng)
cRandom (const char *name=nullptr, cRNG *rng=nullptr)
virtual ~cRandom ()
virtual void setRNG (cRNG *rng)
cRNG * getRNG () const
Public Member Functions inherited from cOwnedObject
cOwnedObject ()
cOwnedObject (const char *name, bool namepooling=true)
cOwnedObject (const cOwnedObject &obj)
virtual ~cOwnedObject ()
cOwnedObject & operator= (const cOwnedObject &o)
virtual cObject * getOwner () const override
virtual bool isOwnedObject () const override
virtual bool isSoftOwner () const
Public Member Functions inherited from cNamedObject
cNamedObject ()
cNamedObject (const char *name, bool namepooling=true)
cNamedObject (const cNamedObject &obj)
virtual ~cNamedObject ()
cNamedObject & operator= (const cNamedObject &o)
virtual void setName (const char *s)
virtual const char * getName () const override
virtual void setNamePooling (bool b)
virtual bool getNamePooling ()
Public Member Functions inherited from cObject
cObject ()
cObject (const cObject &other)
virtual ~cObject ()
virtual const char * getClassName () const
bool isName (const char *s) const
virtual const char * getFullName () const
virtual std::string getFullPath () const
const cObject * getThisPtr () const
virtual _OPPDEPRECATED std::string info () const
virtual _OPPDEPRECATED std::string detailedInfo () const
virtual void forEachChild (cVisitor *v)
cObject * findObject (const char *name, bool deep=true)
void copyNotSupported () const
Additional Inherited Members
Public Types inherited from cPrecollectionBasedDensityEst
enum RangeMode
Constants for histogram range_mode.
Static Public Member Functions inherited from cOwnedObject
static long getTotalObjectCount ()
static long getLiveObjectCount ()
static void resetObjectCounters ()
static cDefaultList * getDefaultOwner ()
Protected Member Functions inherited from cLegacyHistogram
virtual void collectIntoHistogram (double value) override
virtual void collectWeightedIntoHistogram (double value, double weight) override
virtual void setupRange () override
Protected Member Functions inherited from cObject
virtual void take (cOwnedObject *obj)
virtual void drop (cOwnedObject *obj)
void dropAndDelete (cOwnedObject *obj)
Constructor & Destructor Documentation
cLongHistogram() [1/2]
cLongHistogram (const cLongHistogram & r) inline
Copy constructor.
cLongHistogram() [2/2]
cLongHistogram (const char * name = nullptr, int numcells = -1, bool weighted = false) inline explicit
Constructor.
~cLongHistogram()
virtual ~cLongHistogram () inline virtual
Destructor.
Member Function Documentation
operator=()
cLongHistogram& operator= (const cLongHistogram & other)
Assignment operator.
dup()
virtual cLongHistogram* dup () const inline override virtual
Creates and returns an exact copy of this object. See cObject for more details.
Reimplemented from cAbstractHistogram.
collect() [1/2]
virtual void collect (double value) inline override virtual
Collects one value. Internally, the double value is converted to an integer using floor() before any processing.
Reimplemented from cPrecollectionBasedDensityEst.
References cPrecollectionBasedDensityEst::collect().
collect() [2/2]
virtual void collect (SimTime value) inline override virtual
Convenience method, delegates to collect(double).
Reimplemented from cStatistic.
References cLongHistogram::collect(), and SimTime::dbl().
Referenced by cLongHistogram::collect().
The documentation for this class was generated from the following file:
clegacyhistogram.h