//
// Generated file, do not edit! Created by nedtool 5.6 from tictoc13.msg.
//

#ifndef __TICTOC13_M_H
#define __TICTOC13_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class TicTocMsg13;
/**
 * Class generated from <tt>tictoc13.msg:12</tt> by nedtool.
 * <pre>
 * message TicTocMsg13
 * {
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class TicTocMsg13 : public ::omnetpp::cMessage
{
  protected:
    int source = 0;
    int destination = 0;
    int hopCount = 0;

  private:
    void copy(const TicTocMsg13& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TicTocMsg13&);

  public:
    TicTocMsg13(const char *name=nullptr, short kind=0);
    TicTocMsg13(const TicTocMsg13& other);
    virtual ~TicTocMsg13();
    TicTocMsg13& operator=(const TicTocMsg13& other);
    virtual TicTocMsg13 *dup() const override {return new TicTocMsg13(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TicTocMsg13& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TicTocMsg13& obj) {obj.parsimUnpack(b);}

#endif // ifndef __TICTOC13_M_H

