//
// Generated file, do not edit! Created by nedtool 5.6 from tictoc15.msg.
//

#ifndef __TICTOC15_M_H
#define __TICTOC15_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class TicTocMsg15;
/**
 * Class generated from <tt>tictoc15.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // Same as TictocMsg13
 * //
 * message TicTocMsg15
 * {
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class TicTocMsg15 : public ::omnetpp::cMessage
{
  protected:
    int source = 0;
    int destination = 0;
    int hopCount = 0;

  private:
    void copy(const TicTocMsg15& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TicTocMsg15&);

  public:
    TicTocMsg15(const char *name=nullptr, short kind=0);
    TicTocMsg15(const TicTocMsg15& other);
    virtual ~TicTocMsg15();
    TicTocMsg15& operator=(const TicTocMsg15& other);
    virtual TicTocMsg15 *dup() const override {return new TicTocMsg15(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TicTocMsg15& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TicTocMsg15& obj) {obj.parsimUnpack(b);}

#endif // ifndef __TICTOC15_M_H

