OMNeT++ NEDXML: NedResourceCache::CachedTypeNames Class Reference
NedResourceCache::CachedTypeNames Class Reference
#include <nedresourcecache.h>
Public Member Functions
CachedTypeNames (NedResourceCache *p)
virtual bool contains (const char *qname) const override
virtual int size () const override
virtual const char * get (int k) const override
Public Member Functions inherited from NedResourceCache::INedTypeNames
virtual ~INedTypeNames ()
Protected Attributes
NedResourceCache * p
Constructor & Destructor Documentation
CachedTypeNames()
CachedTypeNames (NedResourceCache * p) inline
Member Function Documentation
contains()
virtual bool contains (const char * qname) const inline override virtual
Returns true if the given fully qualified name is an existing NED type
Implements NedResourceCache::INedTypeNames.
References NedResourceCache::lookup().
size()
virtual int size () const inline override virtual
Returns the number of NED type names
Implements NedResourceCache::INedTypeNames.
References NedResourceCache::getTypeNames().
get()
virtual const char* get (int k) const inline override virtual
Returns the kth fully qualified NED type name
Implements NedResourceCache::INedTypeNames.
References NedResourceCache::getTypeNames().
Member Data Documentation
p
NedResourceCache* p protected
The documentation for this class was generated from the following file:
nedresourcecache.h