OMNeT++ NEDXML: NedResourceCache Class Reference
NedResourceCache Class Reference
NED Resources
#include <nedresourcecache.h>
Description
Stores loaded NED files, and keeps track of components in them.
This class can be turned into a cache (discarding and reloading NED files on demand) if such need arises.
Classes
class CachedTypeNames
class INedTypeNames
struct PendingNedType
Public Member Functions
NedResourceCache ()
virtual ~NedResourceCache ()
virtual int loadNedSourceFolder (const char *foldername)
virtual void loadNedFile (const char *nedfname, const char *expectedPackage, bool isXML)
virtual void loadNedText (const char *name, const char *nedtext, const char *expectedPackage, bool isXML)
virtual void doneLoadingNedFiles ()
virtual bool addFile (const char *fname, ASTNode *node)
virtual ASTNode * getFile (const char *fname) const
virtual NedFileElement * getParentPackageNedFile (NedFileElement *nedfile) const
virtual NedTypeInfo * lookup (const char *qname) const
virtual NedTypeInfo * getDecl (const char *qname) const
virtual std::string resolveNedType (const NedLookupContext &context, const char *nedtypename, INedTypeNames *qnames)
virtual std::string resolveNedType (const NedLookupContext &context, const char *nedtypename)
virtual const std::vector< std::string > & getTypeNames () const
virtual std::string getNedPackageForFolder (const char *folder) const
Static Public Member Functions
static NedLookupContext getParentContextOf (const char *qname, ASTNode *node)
Protected Types
typedef std::map< std::string, ASTNode * > NedFileMap
typedef std::map< std::string, NedTypeInfo * > NedTypeInfoMap
typedef std::map< std::string, std::string > StringMap
Protected Member Functions
virtual void registerBuiltinDeclarations ()
virtual int doLoadNedSourceFolder (const char *foldername, const char *expectedPackage)
virtual void doLoadNedFileOrText (const char *nedfname, const char *nedtext, const char *expectedPackage, bool isXML)
virtual ASTNode * parseAndValidateNedFileOrText (const char *nedfname, const char *nedtext, bool isXML)
virtual std::string determineRootPackageName (const char *nedSourceFolderName)
virtual std::string getNedSourceFolderForFolder (const char *folder) const
virtual void collectNedTypesFrom (ASTNode *node, const std::string &packagePrefix, bool areInnerTypes)
virtual void collectNedType (const char *qname, bool isInnerType, ASTNode *node)
virtual bool areDependenciesResolved (const char *qname, ASTNode *node)
virtual void registerPendingNedTypes ()
virtual void registerNedType (const char *qname, bool isInnerType, ASTNode *node)
virtual std::string getFirstError (ErrorStore *errors, const char *prefix=nullptr)
Protected Attributes
NedFileMap files
NedTypeInfoMap nedTypes
std::vector< std::string > nedTypeNames
StringMap folderPackages
std::vector< PendingNedType > pendingList
Member Typedef Documentation
NedFileMap
typedef std::map<std::string, ASTNode *> NedFileMap protected
NedTypeInfoMap
typedef std::map<std::string, NedTypeInfo *> NedTypeInfoMap protected
StringMap
typedef std::map<std::string,std::string> StringMap protected
Constructor & Destructor Documentation
NedResourceCache()
NedResourceCache ()
Constructor
~NedResourceCache()
virtual ~NedResourceCache () virtual
Destructor
Member Function Documentation
registerBuiltinDeclarations()
virtual void registerBuiltinDeclarations () protected virtual
doLoadNedSourceFolder()
virtual int doLoadNedSourceFolder (const char * foldername, const char * expectedPackage) protected virtual
doLoadNedFileOrText()
virtual void doLoadNedFileOrText (const char * nedfname, const char * nedtext, const char * expectedPackage, bool isXML) protected virtual
parseAndValidateNedFileOrText()
virtual ASTNode* parseAndValidateNedFileOrText (const char * nedfname, const char * nedtext, bool isXML) protected virtual
determineRootPackageName()
virtual std::string determineRootPackageName (const char * nedSourceFolderName) protected virtual
getNedSourceFolderForFolder()
virtual std::string getNedSourceFolderForFolder (const char * folder) const protected virtual
collectNedTypesFrom()
virtual void collectNedTypesFrom (ASTNode * node, const std::string & packagePrefix, bool areInnerTypes) protected virtual
collectNedType()
virtual void collectNedType (const char * qname, bool isInnerType, ASTNode * node) protected virtual
areDependenciesResolved()
virtual bool areDependenciesResolved (const char * qname, ASTNode * node) protected virtual
registerPendingNedTypes()
virtual void registerPendingNedTypes () protected virtual
registerNedType()
virtual void registerNedType (const char * qname, bool isInnerType, ASTNode * node) protected virtual
getFirstError()
virtual std::string getFirstError (ErrorStore * errors, const char * prefix = nullptr) protected virtual
loadNedSourceFolder()
virtual int loadNedSourceFolder (const char * foldername) virtual
Load all NED files from a NED source folder. This involves visiting each subdirectory, and loading all "*.ned" files from there. The given folder is assumed to be the root of the NED package hierarchy. Returns the number of files loaded.
Note: doneLoadingNedFiles() must be called after the last loadNedSourceFolder()/loadNedFile()/loadNedText() call.
loadNedFile()
virtual void loadNedFile (const char * nedfname, const char * expectedPackage, bool isXML) virtual
Load a single NED file. If the expected package is given (non-nullptr), it should match the package declaration inside the NED file.
Note: doneLoadingNedFiles() must be called after the last loadNedSourceFolder()/loadNedFile()/loadNedText() call.
loadNedText()
virtual void loadNedText (const char * name, const char * nedtext, const char * expectedPackage, bool isXML) virtual
Parses and loads the NED source code passed in the nedtext argument. The name argument will be used as filename in error messages, and and should be unique among the files loaded. If the expected package is given (non-nullptr), it should match the package declaration inside the NED file.
Note: doneLoadingNedFiles() must be called after the last loadNedSourceFolder()/loadNedFile()/loadNedText() call.
doneLoadingNedFiles()
virtual void doneLoadingNedFiles () virtual
To be called after all NED folders / files have been loaded. May be redefined to issue errors for components that could not be fully resolved because of missing base types or interfaces.
addFile()
virtual bool addFile (const char * fname, ASTNode * node) virtual
Add a file (parsed into an object tree) to the cache. If the file was already added, no processing takes place and the function returns false; otherwise it returns true.
getFile()
virtual ASTNode* getFile (const char * fname) const virtual
Get a file (represented as object tree) from the cache
getParentPackageNedFile()
virtual NedFileElement* getParentPackageNedFile (NedFileElement * nedfile) const virtual
Given a NED file, returns the package.ned file from the same folder, or the nearest ancestor package.ned file. If the file is a package.ned file itself, returns the nearest ancestor package.ned file. Returns nullptr if there is no parent package.ned file.
lookup()
virtual NedTypeInfo* lookup (const char * qname) const virtual
Look up a fully qualified NED type name from the cache. Returns nullptr if not found.
Referenced by NedResourceCache::CachedTypeNames::contains().
getDecl()
virtual NedTypeInfo* getDecl (const char * qname) const virtual
Like lookup(), but asserts non-nullptr return value
resolveNedType() [1/2]
virtual std::string resolveNedType (const NedLookupContext & context, const char * nedtypename, INedTypeNames * qnames) virtual
Resolves the given NED type name in the given context, among the given type names. Returns "" if not found.
resolveNedType() [2/2]
virtual std::string resolveNedType (const NedLookupContext & context, const char * nedtypename) inline virtual
Resolves NED type name, based on the NED files loaded
References NedLookupContext::qname.
getTypeNames()
virtual const std::vector<std::string>& getTypeNames () const virtual
Available NED type names
Referenced by NedResourceCache::CachedTypeNames::get(), and NedResourceCache::CachedTypeNames::size().
getNedPackageForFolder()
virtual std::string getNedPackageForFolder (const char * folder) const virtual
Returns the NED package that corresponds to the given folder. Returns "" for the default package, and "-" if the folder is outside all NED folders.
getParentContextOf()
static NedLookupContext getParentContextOf (const char * qname, ASTNode * node) static
Utility method, useful with resolveNedType()/resolveComponentType()
Member Data Documentation
files
NedFileMap files protected
nedTypes
NedTypeInfoMap nedTypes protected
nedTypeNames
std::vector<std::string> nedTypeNames mutable protected
folderPackages
StringMap folderPackages protected
pendingList
std::vector<PendingNedType> pendingList protected
The documentation for this class was generated from the following file:
nedresourcecache.h