#line 1 "lex.msg2yy.cc"

#line 3 "lex.msg2yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer msg2yy_create_buffer
#define yy_delete_buffer msg2yy_delete_buffer
#define yy_scan_buffer msg2yy_scan_buffer
#define yy_scan_string msg2yy_scan_string
#define yy_scan_bytes msg2yy_scan_bytes
#define yy_init_buffer msg2yy_init_buffer
#define yy_flush_buffer msg2yy_flush_buffer
#define yy_load_buffer_state msg2yy_load_buffer_state
#define yy_switch_to_buffer msg2yy_switch_to_buffer
#define yypush_buffer_state msg2yypush_buffer_state
#define yypop_buffer_state msg2yypop_buffer_state
#define yyensure_buffer_stack msg2yyensure_buffer_stack
#define yy_flex_debug msg2yy_flex_debug
#define yyin msg2yyin
#define yyleng msg2yyleng
#define yylex msg2yylex
#define yylineno msg2yylineno
#define yyout msg2yyout
#define yyrestart msg2yyrestart
#define yytext msg2yytext
#define yywrap msg2yywrap
#define yyalloc msg2yyalloc
#define yyrealloc msg2yyrealloc
#define yyfree msg2yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define msg2yy_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer msg2yy_create_buffer
#endif

#ifdef yy_delete_buffer
#define msg2yy_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer msg2yy_delete_buffer
#endif

#ifdef yy_scan_buffer
#define msg2yy_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer msg2yy_scan_buffer
#endif

#ifdef yy_scan_string
#define msg2yy_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string msg2yy_scan_string
#endif

#ifdef yy_scan_bytes
#define msg2yy_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes msg2yy_scan_bytes
#endif

#ifdef yy_init_buffer
#define msg2yy_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer msg2yy_init_buffer
#endif

#ifdef yy_flush_buffer
#define msg2yy_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer msg2yy_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define msg2yy_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state msg2yy_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define msg2yy_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer msg2yy_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define msg2yypush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state msg2yypush_buffer_state
#endif

#ifdef yypop_buffer_state
#define msg2yypop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state msg2yypop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define msg2yyensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack msg2yyensure_buffer_stack
#endif

#ifdef yylex
#define msg2yylex_ALREADY_DEFINED
#else
#define yylex msg2yylex
#endif

#ifdef yyrestart
#define msg2yyrestart_ALREADY_DEFINED
#else
#define yyrestart msg2yyrestart
#endif

#ifdef yylex_init
#define msg2yylex_init_ALREADY_DEFINED
#else
#define yylex_init msg2yylex_init
#endif

#ifdef yylex_init_extra
#define msg2yylex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra msg2yylex_init_extra
#endif

#ifdef yylex_destroy
#define msg2yylex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy msg2yylex_destroy
#endif

#ifdef yyget_debug
#define msg2yyget_debug_ALREADY_DEFINED
#else
#define yyget_debug msg2yyget_debug
#endif

#ifdef yyset_debug
#define msg2yyset_debug_ALREADY_DEFINED
#else
#define yyset_debug msg2yyset_debug
#endif

#ifdef yyget_extra
#define msg2yyget_extra_ALREADY_DEFINED
#else
#define yyget_extra msg2yyget_extra
#endif

#ifdef yyset_extra
#define msg2yyset_extra_ALREADY_DEFINED
#else
#define yyset_extra msg2yyset_extra
#endif

#ifdef yyget_in
#define msg2yyget_in_ALREADY_DEFINED
#else
#define yyget_in msg2yyget_in
#endif

#ifdef yyset_in
#define msg2yyset_in_ALREADY_DEFINED
#else
#define yyset_in msg2yyset_in
#endif

#ifdef yyget_out
#define msg2yyget_out_ALREADY_DEFINED
#else
#define yyget_out msg2yyget_out
#endif

#ifdef yyset_out
#define msg2yyset_out_ALREADY_DEFINED
#else
#define yyset_out msg2yyset_out
#endif

#ifdef yyget_leng
#define msg2yyget_leng_ALREADY_DEFINED
#else
#define yyget_leng msg2yyget_leng
#endif

#ifdef yyget_text
#define msg2yyget_text_ALREADY_DEFINED
#else
#define yyget_text msg2yyget_text
#endif

#ifdef yyget_lineno
#define msg2yyget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno msg2yyget_lineno
#endif

#ifdef yyset_lineno
#define msg2yyset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno msg2yyset_lineno
#endif

#ifdef yywrap
#define msg2yywrap_ALREADY_DEFINED
#else
#define yywrap msg2yywrap
#endif

#ifdef yyalloc
#define msg2yyalloc_ALREADY_DEFINED
#else
#define yyalloc msg2yyalloc
#endif

#ifdef yyrealloc
#define msg2yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc msg2yyrealloc
#endif

#ifdef yyfree
#define msg2yyfree_ALREADY_DEFINED
#else
#define yyfree msg2yyfree
#endif

#ifdef yytext
#define msg2yytext_ALREADY_DEFINED
#else
#define yytext msg2yytext
#endif

#ifdef yyleng
#define msg2yyleng_ALREADY_DEFINED
#else
#define yyleng msg2yyleng
#endif

#ifdef yyin
#define msg2yyin_ALREADY_DEFINED
#else
#define yyin msg2yyin
#endif

#ifdef yyout
#define msg2yyout_ALREADY_DEFINED
#else
#define yyout msg2yyout
#endif

#ifdef yy_flex_debug
#define msg2yy_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug msg2yy_flex_debug
#endif

#ifdef yylineno
#define msg2yylineno_ALREADY_DEFINED
#else
#define yylineno msg2yylineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[242] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  101,   99,   98,   98,   78,   31,
       81,   90,   80,   99,   66,   67,   88,   86,   63,   87,
       72,   89,   26,   26,   64,   62,   91,   65,   92,   73,
       38,   25,   68,   69,   85,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   70,
       79,   71,   82,   99,   61,   60,   60,   61,   36,   32,
       37,  100,   41,   40,   40,   39,   45,   44,   44,   43,
       42,   49,   48,   48,   47,   46,   57,   56,   55,   50,
       51,   53,   54,   52,   94,   77,   76,    0,   29,    1,

        0,   26,    0,    0,   74,   83,   95,   93,   96,   84,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   58,   75,    0,   59,   36,   35,   33,
       34,   39,   47,   30,    0,    0,   28,   27,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   17,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       97,    0,   29,   25,   14,   15,   25,   25,   25,   25,
       11,   25,   25,   25,   18,   25,   25,   25,   25,   25,
       25,   25,   23,   25,   25,   25,    9,   21,   25,   25,

       25,   24,   25,   25,   25,   25,   25,   16,   25,   25,
       25,    3,   25,   25,   19,   25,    5,   25,   25,   25,
        8,   22,    6,   25,   25,   25,   12,    7,   25,   25,
       25,   13,   25,   25,   25,   20,    4,    2,   25,   10,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   27,   27,   28,   27,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   30,   29,   29,
       31,   32,   33,   34,   29,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   29,   51,   52,   53,   54,   29,   29,   55,
       29,   29,   56,   57,   58,   59,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   60,    1,    1,    1,
       61,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   62,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    4,    4,    1,    5,    5,    4,
        1,    1,    1,    1,    1,    1,    5,    5,    6,    6,
        1,    2,    1,    1,    5,    5,    5,    5,    5,    5,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    1,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[253] =
    {   0,
        0,    0,   61,   63,   64,   65,  121,    0,   69,   71,
      183,    0,  243,  299,  448,  449,  449,  449,  424,  449,
      440,  449,  437,    0,  449,  449,  449,  449,  449,  449,
       57,  427,  231,   64,  423,  449,   55,  419,   61,  449,
      449,    0,  449,  449,  449,  405,  391,   44,  390,   40,
      403,   51,  388,  397,   52,  400,   62,  383,   57,  377,
      375,  449,  449,  371,  449,  449,  449,  372,    0,  449,
      449,   86,  449,  449,  449,    0,  449,  449,  449,  449,
      449,  449,  449,  449,    0,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  420,  244,  449,

       88,  249,   95,    0,  449,  449,  449,  449,  449,  449,
        0,  376,  378,  391,  390,  376,  377,  368,  367,  367,
      373,  368,  364,  368,  363,  367,  365,  375,  362,  359,
      355,  356,  348,  449,  449,  323,  449,    0,  449,  449,
      449,    0,    0,  449,  260,   93,   98,    0,  303,  308,
      302,  300,  299,  296,  313,  301,  308,  294,  296,    0,
      303,  291,  303,  304,  295,  288,  215,  299,  294,  288,
      449,  233,  237,  284,    0,    0,  282,  280,  279,  283,
        0,  280,  288,  275,    0,  290,  272,  274,  282,  266,
      270,  280,    0,  275,  274,  279,    0,    0,  262,  272,

      270,    0,  254,  265,  255,  267,  247,    0,  257,  244,
      248,    0,  258,  248,    0,  241,    0,  253,  256,  246,
        0,    0,    0,  250,  234,  231,    0,    0,  247,  243,
      243,    0,  228,  232,  223,    0,    0,    0,   67,    0,
      449,  357,  363,  369,  375,  381,  383,  389,  395,  398,
      401,  113
    } ;

static const flex_int16_t yy_def[253] =
    {   0,
      241,    1,  242,  242,  243,  243,  241,    7,  244,  244,
      241,   11,  245,  245,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  246,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  247,  241,  241,  241,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  248,  241,
      241,  249,  241,  241,  241,  250,  241,  241,  241,  241,
      241,  241,  241,  241,  251,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,

      241,  241,  241,  252,  241,  241,  241,  241,  241,  241,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  241,  241,  241,  241,  248,  241,  241,
      241,  250,  251,  241,  241,  241,  241,  252,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      241,  241,  241,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
        0,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241
    } ;

static const flex_int16_t yy_nxt[512] =
    {   0,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   42,   42,   42,
       43,   16,   44,   45,   46,   47,   48,   49,   50,   51,
       42,   42,   52,   42,   42,   53,   54,   55,   42,   56,
       42,   57,   58,   59,   42,   60,   61,   62,   63,   16,
       16,   64,   66,   67,   66,   67,   70,   70,   71,   71,
       78,   79,   78,   79,   99,   99,  106,  107,   80,  101,
       80,  102,  102,  109,  110,  114,  126,  119,  140,  115,
      141,  103,  116,  117,  120,   72,   72,  122,  123,   81,

      127,   81,  103,  129,  132,   99,   99,  146,  133,  146,
      147,  147,  147,  147,  130,  147,  147,  148,   68,  240,
       68,   73,   74,   75,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   76,   76,   73,   76,   76,
       76,   73,   73,   73,   73,   73,   73,   76,   76,   76,
       76,   73,   73,   73,   73,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   73,   73,   73,   73,
       73,   73,   73,   82,   83,   84,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   85,   85,   82,

       85,   85,   85,   82,   82,   82,   82,   82,   82,   85,
       85,   85,   85,   82,   82,   86,   82,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   82,   82,
       82,   82,   82,   82,   82,   88,  101,   89,  102,  102,
      173,  173,   90,   91,  173,  173,   92,  191,  103,  239,
      104,   99,   99,   93,  101,   94,  102,  102,  192,  103,
      238,  145,  172,   90,  172,   91,  103,  173,  173,  237,
      236,  235,  145,  234,  233,  104,  232,  103,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,   90,  221,

       91,   88,  220,   89,  219,  218,  217,  216,   90,   91,
      215,  214,   92,  213,  212,  211,  210,  209,  208,   93,
      207,   94,  206,  205,  204,  203,  202,  201,  200,   90,
      199,   91,  198,  197,  196,  195,  194,  193,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,   90,  174,   91,   65,   65,   65,
       65,   65,   65,   69,   69,   69,   69,   69,   69,   77,
       77,   77,   77,   77,   77,   87,   87,   87,   87,   87,
       87,   98,   98,  171,   98,   98,   98,  111,  111,  138,
      170,  138,  138,  138,  138,  139,  139,  139,  139,  139,

      139,  142,  142,  142,  143,  143,  143,  169,  168,  167,
      166,  165,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  144,  137,
      136,  135,  134,  131,  128,  125,  124,  121,  118,  113,
      112,  108,  105,  100,   97,   96,   95,  241,   15,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,

      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241
    } ;

static const flex_int16_t yy_chk[512] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    4,    4,    5,    6,    5,    6,
        9,    9,   10,   10,   31,   31,   37,   37,    9,   34,
       10,   34,   34,   39,   39,   48,   55,   50,   72,   48,
       72,   34,   48,   48,   50,    5,    6,   52,   52,    9,

       55,   10,   34,   57,   59,  101,  101,  103,   59,  103,
      146,  146,  103,  103,   57,  147,  147,  252,    3,  239,
        4,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   13,   33,   13,   33,   33,
      172,  172,   13,   13,  173,  173,   13,  167,   33,  235,
       33,   99,   99,   13,  102,   13,  102,  102,  167,   33,
      234,   99,  145,   13,  145,   13,  102,  145,  145,  233,
      231,  230,   99,  229,  226,   33,  225,  102,  224,  220,
      219,  218,  216,  214,  213,  211,  210,  209,   13,  207,

       13,   14,  206,   14,  205,  204,  203,  201,   14,   14,
      200,  199,   14,  196,  195,  194,  192,  191,  190,   14,
      189,   14,  188,  187,  186,  184,  183,  182,  180,   14,
      179,   14,  178,  177,  174,  170,  169,  168,  166,  165,
      164,  163,  162,  161,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,   14,  149,   14,  242,  242,  242,
      242,  242,  242,  243,  243,  243,  243,  243,  243,  244,
      244,  244,  244,  244,  244,  245,  245,  245,  245,  245,
      245,  246,  246,  136,  246,  246,  246,  247,  247,  248,
      133,  248,  248,  248,  248,  249,  249,  249,  249,  249,

      249,  250,  250,  250,  251,  251,  251,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  121,  120,
      119,  118,  117,  116,  115,  114,  113,  112,   98,   68,
       64,   61,   60,   58,   56,   54,   53,   51,   49,   47,
       46,   38,   35,   32,   23,   21,   19,   15,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,

      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "msg2.lex"
/*==================================================
 * File: msg2.lex
 *
 *  Lexical analyser for OMNeT++ MSG-2.
 *
 *  Author: Andras Varga
 *
 ==================================================*/
/*--------------------------------------------------------------*
  Copyright (C) 1992,2005 Andras Varga

  This file is distributed WITHOUT ANY WARRANTY. See the file
  `license' for details on this and other legal matters.
*--------------------------------------------------------------*/
/*
 * MSG-2 reserved words:
 *    non-component:   cplusplus import namespace using
 *    component:       struct message class noncobject enum
 *    inheritance:     extends
 *    field types:     char short int long double unsigned string const true false
 *    field modifiers: abstract
 */






/* the following option keeps isatty() out */
#define YY_NO_UNISTD_H 1
/*%option debug*/
#line 47 "msg2.lex"
#include <cstring>
#include "yydefs.h"
#include "exception.h"
#include "msg2.tab.hh"

#define yylloc msg2yylloc
extern YYSTYPE yylval;
extern YYLTYPE yylloc;

// wrap symbols to allow several .lex files coexist
#define comment     msgcomment
#define countChars  msgcount
#define extendCount msgextendCount
#define debugPrint  msgdebugPrint

void comment();
void countChars();
void extendCount();
int debugPrint(int c);

static bool recognizeObsoleteKeywords = false;
static bool recognizeNewKeywords = true;

static int parenDepth = 0;

#define P(x)  (x)
//#define P(x)  debugPrint(x)  /*for debugging*/

using namespace omnetpp::nedxml;

#pragma GCC diagnostic ignored "-Wsign-compare"  // suppress warning in bison template code

#line 962 "lex.msg2yy.cc"
#line 963 "lex.msg2yy.cc"

#define INITIAL 0
#define cplusplusbody 1
#define stringliteral 2
#define propertyname 3
#define afterpropertyname 4
#define propertyindex 5
#define propertyvalue 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 81 "msg2.lex"

#line 1188 "lex.msg2yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 242 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 241 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 82 "msg2.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 84 "msg2.lex"
{ countChars(); return NAMESPACE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 85 "msg2.lex"
{ countChars(); return recognizeNewKeywords ? USING : NAME; /*reserved for future use*/ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 86 "msg2.lex"
{ countChars(); return CPLUSPLUS; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "msg2.lex"
{ countChars(); return recognizeNewKeywords ? IMPORT : NAME; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 88 "msg2.lex"
{ countChars(); return STRUCT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 89 "msg2.lex"
{ countChars(); return MESSAGE; /*TODO maybe: recognizeObsoleteKeywords ? MESSAGE : NAME;*/ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 90 "msg2.lex"
{ countChars(); return PACKET; /*TODO maybe: recognizeObsoleteKeywords ? PACKET : NAME;*/ }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 91 "msg2.lex"
{ countChars(); return CLASS; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 92 "msg2.lex"
{ countChars(); return NONCOBJECT; /*TODO maybe: recognizeObsoleteKeywords ? NONCOBJECT : NAME;*/ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 93 "msg2.lex"
{ countChars(); return ENUM; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 94 "msg2.lex"
{ countChars(); return EXTENDS; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 95 "msg2.lex"
{ countChars(); return ABSTRACT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 97 "msg2.lex"
{ countChars(); return BOOLTYPE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 98 "msg2.lex"
{ countChars(); return CHARTYPE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 99 "msg2.lex"
{ countChars(); return SHORTTYPE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 100 "msg2.lex"
{ countChars(); return INTTYPE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 101 "msg2.lex"
{ countChars(); return LONGTYPE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 102 "msg2.lex"
{ countChars(); return DOUBLETYPE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 103 "msg2.lex"
{ countChars(); return UNSIGNED_; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 104 "msg2.lex"
{ countChars(); return recognizeNewKeywords ? CONST_ : NAME; /*reserved for future use*/ }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 105 "msg2.lex"
{ countChars(); return STRINGTYPE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 106 "msg2.lex"
{ countChars(); return TRUE_; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 107 "msg2.lex"
{ countChars(); return FALSE_; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 109 "msg2.lex"
{ countChars(); return NAME; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 110 "msg2.lex"
{ countChars(); return INTCONSTANT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 111 "msg2.lex"
{ countChars(); return INTCONSTANT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 112 "msg2.lex"
{ countChars(); return REALCONSTANT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 113 "msg2.lex"
{ countChars(); return REALCONSTANT; }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 114 "msg2.lex"
{ countChars(); return CHARCONSTANT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 116 "msg2.lex"
{ countChars(); BEGIN(stringliteral); }
	YY_BREAK

case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 118 "msg2.lex"
{ BEGIN(INITIAL); parenDepth=0; throw NedException("Unterminated string literal"); }
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 119 "msg2.lex"
{ extendCount(); /* line continuation */ }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 120 "msg2.lex"
{ extendCount(); /* qouted quote */ }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 121 "msg2.lex"
{ extendCount(); /* qouted char */ }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 122 "msg2.lex"
{ extendCount(); /* character inside string literal */ }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 123 "msg2.lex"
{ extendCount(); if (parenDepth==0) BEGIN(INITIAL);else BEGIN(propertyvalue); return STRINGCONSTANT; /* closing quote */ }
	YY_BREAK

case 38:
YY_RULE_SETUP
#line 126 "msg2.lex"
{ countChars(); BEGIN(propertyname); return '@'; }
	YY_BREAK

case 39:
YY_RULE_SETUP
#line 128 "msg2.lex"
{ countChars(); BEGIN(afterpropertyname); return PROPNAME; }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 129 "msg2.lex"
{ countChars(); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 130 "msg2.lex"
{ BEGIN(INITIAL); yyless(0); }
	YY_BREAK


case 42:
YY_RULE_SETUP
#line 134 "msg2.lex"
{ countChars(); BEGIN(propertyindex); return P('['); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 135 "msg2.lex"
{ countChars(); BEGIN(propertyvalue); parenDepth=1; return P('('); }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 136 "msg2.lex"
{ countChars(); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 137 "msg2.lex"
{ BEGIN(INITIAL); yyless(0); }
	YY_BREAK


case 46:
YY_RULE_SETUP
#line 141 "msg2.lex"
{ countChars(); BEGIN(afterpropertyname); return P(']'); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 142 "msg2.lex"
{ countChars(); return PROPNAME; }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 143 "msg2.lex"
{ countChars(); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 144 "msg2.lex"
{ BEGIN(INITIAL); yyless(0); }
	YY_BREAK


case 50:
YY_RULE_SETUP
#line 148 "msg2.lex"
{ countChars(); ++parenDepth; return P(CHAR); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 149 "msg2.lex"
{ countChars(); if (--parenDepth==0) {BEGIN(INITIAL); return P(yytext[0]);} else return P(CHAR); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 150 "msg2.lex"
{ countChars(); return P(parenDepth==1 ? '=' : CHAR); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 151 "msg2.lex"
{ countChars(); return P(parenDepth==1 ? ',' : CHAR); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 152 "msg2.lex"
{ countChars(); return P(parenDepth==1 ? ';' : CHAR); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 153 "msg2.lex"
{ countChars(); BEGIN(stringliteral); }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 154 "msg2.lex"
{ countChars(); return P(CHAR); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 155 "msg2.lex"
{ countChars(); return P(CHAR); }
	YY_BREAK

case 58:
YY_RULE_SETUP
#line 158 "msg2.lex"
{ countChars(); BEGIN(cplusplusbody); }
	YY_BREAK

case 59:
YY_RULE_SETUP
#line 160 "msg2.lex"
{ extendCount(); BEGIN(INITIAL); return CPLUSPLUSBODY; }
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 161 "msg2.lex"
{ extendCount(); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 162 "msg2.lex"
{ extendCount(); }
	YY_BREAK

case 62:
YY_RULE_SETUP
#line 165 "msg2.lex"
{ countChars(); return ';'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 166 "msg2.lex"
{ countChars(); return ','; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 167 "msg2.lex"
{ countChars(); return ':'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 168 "msg2.lex"
{ countChars(); return '='; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 169 "msg2.lex"
{ countChars(); return '('; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 170 "msg2.lex"
{ countChars(); return ')'; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 171 "msg2.lex"
{ countChars(); return '['; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 172 "msg2.lex"
{ countChars(); return ']'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 173 "msg2.lex"
{ countChars(); return '{'; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 174 "msg2.lex"
{ countChars(); return '}'; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 175 "msg2.lex"
{ countChars(); return '.'; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 176 "msg2.lex"
{ countChars(); return '?'; }
	YY_BREAK
/* XXX are the next ones really needed? */
case 74:
YY_RULE_SETUP
#line 180 "msg2.lex"
{ countChars(); return DOUBLECOLON; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 181 "msg2.lex"
{ countChars(); return OR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 182 "msg2.lex"
{ countChars(); return AND; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 183 "msg2.lex"
{ countChars(); return XOR; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 184 "msg2.lex"
{ countChars(); return NOT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 186 "msg2.lex"
{ countChars(); return BIN_OR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 187 "msg2.lex"
{ countChars(); return BIN_AND; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 188 "msg2.lex"
{ countChars(); return BIN_XOR; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 189 "msg2.lex"
{ countChars(); return BIN_COMPL; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 190 "msg2.lex"
{ countChars(); return SHIFT_LEFT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 191 "msg2.lex"
{ countChars(); return SHIFT_RIGHT; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 193 "msg2.lex"
{ countChars(); return '^'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 194 "msg2.lex"
{ countChars(); return '+'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 195 "msg2.lex"
{ countChars(); return '-'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 196 "msg2.lex"
{ countChars(); return '*'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 197 "msg2.lex"
{ countChars(); return '/'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 198 "msg2.lex"
{ countChars(); return '%'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 199 "msg2.lex"
{ countChars(); return '<'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 200 "msg2.lex"
{ countChars(); return '>'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 202 "msg2.lex"
{ countChars(); return EQ; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 203 "msg2.lex"
{ countChars(); return NE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 204 "msg2.lex"
{ countChars(); return LE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 205 "msg2.lex"
{ countChars(); return GE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 207 "msg2.lex"
{ /* UTF-8 BOM mark, ignore */ }
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 208 "msg2.lex"
{ countChars(); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 209 "msg2.lex"
{ countChars(); return INVALID_CHAR; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 211 "msg2.lex"
ECHO;
	YY_BREAK
#line 1763 "lex.msg2yy.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(cplusplusbody):
case YY_STATE_EOF(stringliteral):
case YY_STATE_EOF(propertyname):
case YY_STATE_EOF(afterpropertyname):
case YY_STATE_EOF(propertyindex):
case YY_STATE_EOF(propertyvalue):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 242 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 242 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 241);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 211 "msg2.lex"


namespace omnetpp {
namespace nedxml {

void msgLexerSetRecognizeNewKeywords(bool opt)
{
    recognizeNewKeywords = opt;
}

void msgLexerSetRecognizeObsoleteKeywords(bool opt)
{
    recognizeObsoleteKeywords = opt;
}

} // namespace
} // namespace

int yywrap()
{
     return 1;
}

/*
 * - discards all remaining characters of a line of
 *   text from the inputstream.
 * - the characters are read with the input() and
 *   unput() functions.
 * - input() is sometimes called yyinput()...
 */
#ifdef __cplusplus
#define input  yyinput
#endif

/* the following #define is needed for broken flex versions */
#define yytext_ptr yytext

void comment()
{
    int c;
    while ((c = input())!='\n' && c!=0 && c!=EOF);
    if (c=='\n') unput(c);
}

/*
 * - counts the line and column number of the current token in `pos'
 * - yytext[] is the current token passed by (f)lex
 */
static void _count(bool updateprevpos)
{
    int i;

    // printf("DBG: countChars(): prev=%d,%d  pos=%d,%d yytext=>>%s<<\n", prevpos.li, prevpos.co, pos.li, pos.co, yytext);

    if (pos.li==1 && pos.co==0)
        parenDepth = 0;

    if (updateprevpos)
        prevpos = pos;

    for (i = 0; yytext[i] != '\0'; i++) {
        if (yytext[i] == '\n') {
            pos.co = 0;
            pos.li++;
        } else if (yytext[i] == '\t')
            pos.co += 8 - (pos.co % 8);
        else
            pos.co++;
    }

    // printf("count '%s': %d:%d-%d:%d\n", strcmp(yytext,"\n")==0?"\\n":yytext, prevpos.li, prevpos.co, pos.li, pos.co);
    yylloc.first_line   = prevpos.li;
    yylloc.first_column = prevpos.co;
    yylloc.last_line    = pos.li;
    yylloc.last_column  = pos.co;
}

void countChars()
{
    _count(true);
}

void extendCount()
{
    _count(false);
}

int debugPrint(int c)
{
    if (c==CHAR) fprintf(stderr, " ret=CHAR\n");
    else if (c==STRINGCONSTANT) fprintf(stderr, " ret=STRINGCONSTANT\n");
    else if (c>0 && c<=255) fprintf(stderr, " ret='%c'\n", c);
    else fprintf(stderr, " ret=%d\n", c);
    return c;
}

