#line 1 "lex.ned2yy.cc"

#line 3 "lex.ned2yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ned2yy_create_buffer
#define yy_delete_buffer ned2yy_delete_buffer
#define yy_scan_buffer ned2yy_scan_buffer
#define yy_scan_string ned2yy_scan_string
#define yy_scan_bytes ned2yy_scan_bytes
#define yy_init_buffer ned2yy_init_buffer
#define yy_flush_buffer ned2yy_flush_buffer
#define yy_load_buffer_state ned2yy_load_buffer_state
#define yy_switch_to_buffer ned2yy_switch_to_buffer
#define yypush_buffer_state ned2yypush_buffer_state
#define yypop_buffer_state ned2yypop_buffer_state
#define yyensure_buffer_stack ned2yyensure_buffer_stack
#define yy_flex_debug ned2yy_flex_debug
#define yyin ned2yyin
#define yyleng ned2yyleng
#define yylex ned2yylex
#define yylineno ned2yylineno
#define yyout ned2yyout
#define yyrestart ned2yyrestart
#define yytext ned2yytext
#define yywrap ned2yywrap
#define yyalloc ned2yyalloc
#define yyrealloc ned2yyrealloc
#define yyfree ned2yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define ned2yy_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer ned2yy_create_buffer
#endif

#ifdef yy_delete_buffer
#define ned2yy_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer ned2yy_delete_buffer
#endif

#ifdef yy_scan_buffer
#define ned2yy_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer ned2yy_scan_buffer
#endif

#ifdef yy_scan_string
#define ned2yy_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string ned2yy_scan_string
#endif

#ifdef yy_scan_bytes
#define ned2yy_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes ned2yy_scan_bytes
#endif

#ifdef yy_init_buffer
#define ned2yy_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer ned2yy_init_buffer
#endif

#ifdef yy_flush_buffer
#define ned2yy_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer ned2yy_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define ned2yy_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state ned2yy_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define ned2yy_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer ned2yy_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define ned2yypush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state ned2yypush_buffer_state
#endif

#ifdef yypop_buffer_state
#define ned2yypop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state ned2yypop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define ned2yyensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack ned2yyensure_buffer_stack
#endif

#ifdef yylex
#define ned2yylex_ALREADY_DEFINED
#else
#define yylex ned2yylex
#endif

#ifdef yyrestart
#define ned2yyrestart_ALREADY_DEFINED
#else
#define yyrestart ned2yyrestart
#endif

#ifdef yylex_init
#define ned2yylex_init_ALREADY_DEFINED
#else
#define yylex_init ned2yylex_init
#endif

#ifdef yylex_init_extra
#define ned2yylex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra ned2yylex_init_extra
#endif

#ifdef yylex_destroy
#define ned2yylex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy ned2yylex_destroy
#endif

#ifdef yyget_debug
#define ned2yyget_debug_ALREADY_DEFINED
#else
#define yyget_debug ned2yyget_debug
#endif

#ifdef yyset_debug
#define ned2yyset_debug_ALREADY_DEFINED
#else
#define yyset_debug ned2yyset_debug
#endif

#ifdef yyget_extra
#define ned2yyget_extra_ALREADY_DEFINED
#else
#define yyget_extra ned2yyget_extra
#endif

#ifdef yyset_extra
#define ned2yyset_extra_ALREADY_DEFINED
#else
#define yyset_extra ned2yyset_extra
#endif

#ifdef yyget_in
#define ned2yyget_in_ALREADY_DEFINED
#else
#define yyget_in ned2yyget_in
#endif

#ifdef yyset_in
#define ned2yyset_in_ALREADY_DEFINED
#else
#define yyset_in ned2yyset_in
#endif

#ifdef yyget_out
#define ned2yyget_out_ALREADY_DEFINED
#else
#define yyget_out ned2yyget_out
#endif

#ifdef yyset_out
#define ned2yyset_out_ALREADY_DEFINED
#else
#define yyset_out ned2yyset_out
#endif

#ifdef yyget_leng
#define ned2yyget_leng_ALREADY_DEFINED
#else
#define yyget_leng ned2yyget_leng
#endif

#ifdef yyget_text
#define ned2yyget_text_ALREADY_DEFINED
#else
#define yyget_text ned2yyget_text
#endif

#ifdef yyget_lineno
#define ned2yyget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno ned2yyget_lineno
#endif

#ifdef yyset_lineno
#define ned2yyset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno ned2yyset_lineno
#endif

#ifdef yywrap
#define ned2yywrap_ALREADY_DEFINED
#else
#define yywrap ned2yywrap
#endif

#ifdef yyalloc
#define ned2yyalloc_ALREADY_DEFINED
#else
#define yyalloc ned2yyalloc
#endif

#ifdef yyrealloc
#define ned2yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc ned2yyrealloc
#endif

#ifdef yyfree
#define ned2yyfree_ALREADY_DEFINED
#else
#define yyfree ned2yyfree
#endif

#ifdef yytext
#define ned2yytext_ALREADY_DEFINED
#else
#define yytext ned2yytext
#endif

#ifdef yyleng
#define ned2yyleng_ALREADY_DEFINED
#else
#define yyleng ned2yyleng
#endif

#ifdef yyin
#define ned2yyin_ALREADY_DEFINED
#else
#define yyin ned2yyin
#endif

#ifdef yyout
#define ned2yyout_ALREADY_DEFINED
#else
#define yyout ned2yyout
#endif

#ifdef yy_flex_debug
#define ned2yy_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug ned2yy_flex_debug
#endif

#ifdef yylineno
#define ned2yylineno_ALREADY_DEFINED
#else
#define yylineno ned2yylineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 120
#define YY_END_OF_BUFFER 121
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[341] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  121,  119,  118,  118,   98,   53,  101,   82,
      110,  100,   87,   88,  108,  106,   84,  107,   93,  109,
       49,   49,   85,   83,  111,   86,  112,   94,   60,   48,
       89,  119,   90,  105,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   91,   99,   92,  102,   58,   54,   59,  120,   63,
       62,   62,   61,   67,   66,   66,   65,   64,   71,   70,
       70,   69,   68,   79,   78,   77,   72,   73,   75,   76,
       74,  114,   97,   96,   80,   81,    0,   34,   52,    2,

        0,   49,    0,    0,    0,  103,  115,  113,  116,  104,
        0,   48,    0,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   29,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   95,   58,   57,   55,   56,   61,   69,   31,
        0,    0,   51,   50,   32,    0,    0,   48,   41,   48,
       48,   48,   48,   48,   48,   48,   48,   30,   48,   48,
       48,   38,   48,   48,   21,   48,   48,   37,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   24,    0,   52,   33,    0,    0,   48,   23,   48,

       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   13,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   39,   35,   48,   48,   48,    0,    0,
       48,   48,   48,   42,   48,   48,   48,   48,   36,   16,
       48,   44,   28,   26,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   14,   48,   48,    1,    0,
       48,   48,   48,   48,   20,   45,   48,    3,    6,   48,
       27,   48,   48,   48,    7,   43,   22,   48,   48,   48,
       47,    0,   48,    9,   48,   40,   12,   48,    8,    4,
       48,   48,   48,   48,   48,    0,   48,   48,   48,   48,

       48,    5,   48,   46,   25,    0,   48,   48,   48,   48,
       48,   48,    0,   48,   48,   48,   48,   15,   17,    0,
       48,   48,   18,   48,  117,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   10,   19,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   27,   27,   29,   30,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   32,   31,   31,
       33,   34,   35,   36,   31,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   31,   46,   47,   48,   49,
       50,   51,   31,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,

       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    4,    4,    1,    5,    5,    4,
        1,    1,    1,    1,    3,    1,    5,    5,    5,    5,
        6,    6,    1,    2,    1,    1,    5,    5,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        3,    1,    3,    1
    } ;

static const flex_int16_t yy_base[350] =
    {   0,
        0,    0,   62,   63,   97,    0,  160,  162,  195,    0,
      257,  318,  541,  542,  542,  542,  517,  542,  533,  542,
      542,  529,  542,  542,  525,  523,  542,  520,   53,  517,
      245,  150,  542,  542,   55,  510,   50,  542,  491,    0,
      542,  473,  542,  542,   28,  480,   32,   38,  471,   43,
      491,   41,  482,  476,   50,  470,  130,   40,  129,  474,
      475,  542,  460,  542,  542,    0,  542,  542,   81,  542,
      542,  542,    0,  542,  542,  542,  542,  542,  542,  542,
      542,    0,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  497,  542,  247,  542,

      156,  254,  165,    0,  505,  542,  542,  542,  542,  542,
      461,    0,  489,  470,  470,  465,  477,  464,  470,  456,
      131,  463,  457,  454,    0,  456,  247,  460,  465,  455,
      449,  448,  138,  451,  221,  448,  461,  453,  442,  445,
      448,  447,  542,    0,  542,  542,  542,    0,    0,  542,
      281,  168,  266,    0,  469,  441,  461,  440,    0,  442,
      439,  226,  450,  448,  432,  443,  430,    0,  441,  431,
      439,    0,  424,  423,    0,  436,  421,    0,  418,  423,
      427,  435,  420,  419,  428,  423,  419,  413,  424,  423,
      426,  422,  286,  288,  542,  409,  426,  402,    0,  409,

      416,  402,  400,  407,  399,  403,  410,  397,  397,  390,
      393,  392,    0,  398,  394,  388,  405,  393,  399,  392,
      388,  388,  386,    0,    0,  259,  381,  384,  407,  374,
      376,  389,  390,    0,  381,  386,  373,  385,    0,    0,
      370,    0,    0,    0,  382,  370,  367,  360,  339,  326,
      336,  334,  332,  334,  336,    0,  327,  332,  542,  342,
      320,  321,  313,  312,    0,    0,  312,    0,  319,  317,
        0,  321,  307,  306,    0,    0,    0,  304,  310,  310,
        0,  328,  316,  309,  307,    0,    0,  301,    0,    0,
      308,  289,  300,  305,  304,  310,  293,  293,  290,  284,

      285,    0,  295,    0,    0,  277,  285,  279,  282,  289,
      274,  273,  297,  275,  281,  266,  265,    0,    0,  286,
      274,  262,    0,  271,  542,  272,  268,  272,  248,  256,
      252,  241,  155,  151,  149,  130,    0,    0,    0,  542,
      381,  387,  393,  395,  401,  407,  410,  414,   87
    } ;

static const flex_int16_t yy_def[350] =
    {   0,
      340,    1,  341,  341,  340,    5,  342,  342,  340,    9,
      343,  343,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  344,
      340,  340,  340,  340,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  340,  340,  340,  340,  345,  340,  340,  346,  340,
      340,  340,  347,  340,  340,  340,  340,  340,  340,  340,
      340,  348,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,

      340,  340,  340,  349,  340,  340,  340,  340,  340,  340,
      340,  344,  340,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  340,  345,  340,  340,  340,  347,  348,  340,
      340,  340,  340,  349,  340,  340,  340,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  340,  340,  340,  340,  340,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  340,  340,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  340,  340,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  340,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  340,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  340,  344,  344,  344,  344,
      344,  344,  340,  344,  344,  344,  344,  344,  344,  340,
      344,  344,  344,  344,  340,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,    0,
      340,  340,  340,  340,  340,  340,  340,  340,  340
    } ;

static const flex_int16_t yy_nxt[607] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   40,   40,   40,
       40,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   40,   52,   40,   53,   54,   55,   56,
       57,   40,   58,   59,   40,   60,   40,   61,   40,   40,
       62,   63,   64,   65,   67,   67,   68,   68,   98,  105,
       99,   99,  109,  110,  114,  117,  106,  107,  119,  122,
      115,  118,  125,  146,  135,  147,  130,  120,  126,  127,
      131,  154,  123,  136,  137,   69,   69,   70,   71,   72,

       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   73,   73,   70,   73,   73,   73,   70,   70,   70,
       70,   70,   70,   73,   73,   73,   73,   73,   73,   70,
       70,   70,   70,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   70,   70,   70,
       70,   75,   76,   75,   76,  101,  133,  102,  102,   77,
      339,   77,  138,   99,   99,  165,  181,  152,  103,  152,
      139,  134,  153,  153,  166,  153,  153,  140,  338,  182,
      103,  337,   78,  336,   78,   79,   80,   81,   79,   79,

       79,   79,   79,   79,   79,   79,   82,   79,   79,   82,
       82,   79,   82,   82,   82,   79,   79,   79,   79,   82,
       79,   82,   82,   82,   82,   82,   82,   79,   79,   83,
       79,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   79,   82,   79,   85,
      101,   86,  102,  102,   99,   99,   87,   88,  184,  101,
       89,  102,  102,  103,  201,  151,  104,   90,  202,   91,
      185,  335,  103,  153,  153,  103,  171,  151,  172,   87,
      334,   88,  333,  193,  103,  193,  173,  174,  194,  194,

      175,  332,  104,  194,  194,  194,  194,  255,  331,  330,
      329,  256,  328,  327,  326,  325,  324,   87,  323,   88,
       85,  322,   86,  321,  320,  319,  318,   87,   88,  317,
      316,   89,  315,  314,  313,  312,  311,  310,   90,  309,
       91,  308,  307,  306,  305,  304,  303,  302,  301,  300,
       87,  299,   88,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  276,  275,  274,   87,  273,
       88,   66,   66,   66,   66,   66,   66,   74,   74,   74,
       74,   74,   74,   84,   84,   84,   84,   84,   84,  112,

      112,  144,  272,  144,  144,  144,  144,  145,  145,  145,
      145,  145,  145,  148,  148,  148,  149,  149,  149,  149,
      271,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  203,  200,  199,  198,
      197,  196,  195,  192,  191,  190,  189,  188,  187,  186,

      183,  180,  179,  178,  177,  176,  170,  169,  168,  167,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      150,  143,  142,  141,  132,  129,  128,  124,  121,  116,
      113,  111,  108,  100,   97,   96,   95,   94,   93,   92,
      340,   13,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,

      340,  340,  340,  340,  340,  340
    } ;

static const flex_int16_t yy_chk[607] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,   29,   35,
       29,   29,   37,   37,   45,   47,   35,   35,   48,   50,
       45,   47,   52,   69,   58,   69,   55,   48,   52,   52,
       55,  349,   50,   58,   58,    3,    4,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    7,    7,    8,    8,   32,   57,   32,   32,    7,
      336,    8,   59,  101,  101,  121,  133,  103,   32,  103,
       59,   57,  103,  103,  121,  152,  152,   59,  335,  133,
       32,  334,    7,  333,    8,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,   11,
       31,   11,   31,   31,   99,   99,   11,   11,  135,  102,
       11,  102,  102,   31,  162,   99,   31,   11,  162,   11,
      135,  332,  102,  153,  153,   31,  127,   99,  127,   11,
      331,   11,  330,  151,  102,  151,  127,  127,  151,  151,

      127,  329,   31,  193,  193,  194,  194,  226,  328,  327,
      326,  226,  324,  322,  321,  320,  317,   11,  316,   11,
       12,  315,   12,  314,  313,  312,  311,   12,   12,  310,
      309,   12,  308,  307,  306,  303,  301,  300,   12,  299,
       12,  298,  297,  296,  295,  294,  293,  292,  291,  288,
       12,  285,   12,  284,  283,  282,  280,  279,  278,  274,
      273,  272,  270,  269,  267,  264,  263,  262,  261,  260,
      258,  257,  255,  254,  253,  252,  251,  250,   12,  249,
       12,  341,  341,  341,  341,  341,  341,  342,  342,  342,
      342,  342,  342,  343,  343,  343,  343,  343,  343,  344,

      344,  345,  248,  345,  345,  345,  345,  346,  346,  346,
      346,  346,  346,  347,  347,  347,  348,  348,  348,  348,
      247,  246,  245,  241,  238,  237,  236,  235,  233,  232,
      231,  230,  229,  228,  227,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  198,  197,
      196,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  177,  176,  174,  173,  171,
      170,  169,  167,  166,  165,  164,  163,  161,  160,  158,
      157,  156,  155,  142,  141,  140,  139,  138,  137,  136,

      134,  132,  131,  130,  129,  128,  126,  124,  123,  122,
      120,  119,  118,  117,  116,  115,  114,  113,  111,  105,
       97,   63,   61,   60,   56,   54,   53,   51,   49,   46,
       42,   39,   36,   30,   28,   26,   25,   22,   19,   17,
       13,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,

      340,  340,  340,  340,  340,  340
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ned2.lex"
/*==================================================
 * File: ned2.lex
 *
 *  Lexical analyser for OMNeT++ NED-2.
 *
 *  Author: Andras Varga
 *
 ==================================================*/
/*--------------------------------------------------------------*
  Copyright (C) 1992,2005 Andras Varga

  This file is distributed WITHOUT ANY WARRANTY. See the file
  `license' for details on this and other legal matters.
*--------------------------------------------------------------*/
/*
 * NED-2 reserved words:
 *    non-component: import package property
 *    component:     module simple network channel interface
 *    inheritance:   extends like
 *    sections:      types parameters gates submodules connections allowunconnected
 *    param types:   double int string bool xml volatile
 *    gate types:    input output inout
 *    conditional:   if
 *    connections:   --> <-- <--> while ..
 *    expressions:   true false default const sizeof index xmldoc
 */





/* the following option keeps isatty() out */
#define YY_NO_UNISTD_H 1
/*%option debug*/
#line 50 "ned2.lex"
#include <cstring>
#include "yydefs.h"
#include "exception.h"
#include "ned2.tab.hh"

#define yylloc ned2yylloc
extern YYSTYPE yylval;
extern YYLTYPE yylloc;

// wrap symbols to allow several .lex files coexist
#define comment     ned2comment
#define countChars  ned2count
#define extendCount ned2extendCount
#define debugPrint  ned2debugPrint

void comment();
void countChars();
void extendCount();
int debugPrint(int c);

static int parenDepth = 0;

#define P(x)  (x)
//#define P(x)  debugPrint(x)  /*for debugging*/

#pragma GCC diagnostic ignored "-Wsign-compare"  // suppress warning in bison template code

using namespace omnetpp::nedxml;

#line 1012 "lex.ned2yy.cc"
#line 1013 "lex.ned2yy.cc"

#define INITIAL 0
#define stringliteral 1
#define propertyname 2
#define afterpropertyname 3
#define propertyindex 4
#define propertyvalue 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 81 "ned2.lex"

#line 1237 "lex.ned2yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 341 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 340 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 82 "ned2.lex"
{ return EXPRESSION_SELECTOR; /* must agree with nedparser.cc */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 84 "ned2.lex"
{ comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 86 "ned2.lex"
{ countChars(); return IMPORT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 87 "ned2.lex"
{ countChars(); return PACKAGE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 88 "ned2.lex"
{ countChars(); return PROPERTY; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 90 "ned2.lex"
{ countChars(); return MODULE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "ned2.lex"
{ countChars(); return SIMPLE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 92 "ned2.lex"
{ countChars(); return NETWORK; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "ned2.lex"
{ countChars(); return CHANNEL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "ned2.lex"
{ countChars(); return MODULEINTERFACE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 95 "ned2.lex"
{ countChars(); return CHANNELINTERFACE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "ned2.lex"
{ countChars(); return EXTENDS; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "ned2.lex"
{ countChars(); return LIKE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "ned2.lex"
{ countChars(); return TYPES; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 101 "ned2.lex"
{ countChars(); return PARAMETERS; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 102 "ned2.lex"
{ countChars(); return GATES; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 103 "ned2.lex"
{ countChars(); return SUBMODULES; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 104 "ned2.lex"
{ countChars(); return CONNECTIONS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 105 "ned2.lex"
{ countChars(); return ALLOWUNCONNECTED; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "ned2.lex"
{ countChars(); return DOUBLETYPE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "ned2.lex"
{ countChars(); return INTTYPE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "ned2.lex"
{ countChars(); return STRINGTYPE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 110 "ned2.lex"
{ countChars(); return BOOLTYPE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 111 "ned2.lex"
{ countChars(); return XMLTYPE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 112 "ned2.lex"
{ countChars(); return VOLATILE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 114 "ned2.lex"
{ countChars(); return INPUT_; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 115 "ned2.lex"
{ countChars(); return OUTPUT_; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 116 "ned2.lex"
{ countChars(); return INOUT_; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 118 "ned2.lex"
{ countChars(); return IF; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 119 "ned2.lex"
{ countChars(); return FOR; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 121 "ned2.lex"
{ countChars(); return RIGHTARROW; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 122 "ned2.lex"
{ countChars(); return LEFTARROW; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 123 "ned2.lex"
{ countChars(); return DBLARROW; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 124 "ned2.lex"
{ countChars(); return TO; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 126 "ned2.lex"
{ countChars(); return TRUE_; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 127 "ned2.lex"
{ countChars(); return FALSE_; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 128 "ned2.lex"
{ countChars(); return NAN_; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 129 "ned2.lex"
{ countChars(); return INF_; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 130 "ned2.lex"
{ countChars(); return THIS_; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 131 "ned2.lex"
{ countChars(); return DEFAULT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 132 "ned2.lex"
{ countChars(); return ASK; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 133 "ned2.lex"
{ countChars(); return CONST_; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 134 "ned2.lex"
{ countChars(); return SIZEOF; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 135 "ned2.lex"
{ countChars(); return INDEX_; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 136 "ned2.lex"
{ countChars(); return EXISTS; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 137 "ned2.lex"
{ countChars(); return TYPENAME; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 138 "ned2.lex"
{ countChars(); return XMLDOC; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 140 "ned2.lex"
{ countChars(); return NAME; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 141 "ned2.lex"
{ countChars(); return INTCONSTANT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 142 "ned2.lex"
{ countChars(); return INTCONSTANT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 143 "ned2.lex"
{ countChars(); return REALCONSTANT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 144 "ned2.lex"
{ countChars(); return REALCONSTANT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 146 "ned2.lex"
{ countChars(); BEGIN(stringliteral); }
	YY_BREAK

case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 148 "ned2.lex"
{ BEGIN(INITIAL); parenDepth=0; throw NedException("Unterminated string literal (append backslash to line for multi-line strings)"); /* NOTE: BEGIN(INITIAL) is important, otherwise parsing of the next file (!) will start from the <stringliteral> state! */ }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 149 "ned2.lex"
{ extendCount(); /* line continuation */ }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 150 "ned2.lex"
{ extendCount(); /* qouted quote */ }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 151 "ned2.lex"
{ extendCount(); /* qouted char */ }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 152 "ned2.lex"
{ extendCount(); /* character inside string literal */ }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 153 "ned2.lex"
{ extendCount(); if (parenDepth==0) BEGIN(INITIAL);else BEGIN(propertyvalue); return STRINGCONSTANT; /* closing quote */ }
	YY_BREAK

case 60:
YY_RULE_SETUP
#line 156 "ned2.lex"
{ countChars(); BEGIN(propertyname); return '@'; }
	YY_BREAK

case 61:
YY_RULE_SETUP
#line 158 "ned2.lex"
{ countChars(); BEGIN(afterpropertyname); return PROPNAME; }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 159 "ned2.lex"
{ countChars(); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 160 "ned2.lex"
{ BEGIN(INITIAL); yyless(0); }
	YY_BREAK


case 64:
YY_RULE_SETUP
#line 164 "ned2.lex"
{ countChars(); BEGIN(propertyindex); return P('['); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 165 "ned2.lex"
{ countChars(); BEGIN(propertyvalue); parenDepth=1; return P('('); }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 166 "ned2.lex"
{ countChars(); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 167 "ned2.lex"
{ BEGIN(INITIAL); yyless(0); }
	YY_BREAK


case 68:
YY_RULE_SETUP
#line 171 "ned2.lex"
{ countChars(); BEGIN(afterpropertyname); return P(']'); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 172 "ned2.lex"
{ countChars(); return PROPNAME; }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 173 "ned2.lex"
{ countChars(); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 174 "ned2.lex"
{ BEGIN(INITIAL); yyless(0); }
	YY_BREAK


case 72:
YY_RULE_SETUP
#line 178 "ned2.lex"
{ countChars(); ++parenDepth; return P(CHAR); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 179 "ned2.lex"
{ countChars(); if (--parenDepth==0) {BEGIN(INITIAL); return P(yytext[0]);} else return P(CHAR); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 180 "ned2.lex"
{ countChars(); return P(parenDepth==1 ? '=' : CHAR); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 181 "ned2.lex"
{ countChars(); return P(parenDepth==1 ? ',' : CHAR); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 182 "ned2.lex"
{ countChars(); return P(parenDepth==1 ? ';' : CHAR); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 183 "ned2.lex"
{ countChars(); BEGIN(stringliteral); }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 184 "ned2.lex"
{ countChars(); return P(CHAR); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 185 "ned2.lex"
{ countChars(); return P(CHAR); }
	YY_BREAK

case 80:
YY_RULE_SETUP
#line 188 "ned2.lex"
{ countChars(); return DOUBLEASTERISK; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 189 "ned2.lex"
{ countChars(); return PLUSPLUS; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 191 "ned2.lex"
{ countChars(); return '$'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 192 "ned2.lex"
{ countChars(); return ';'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 193 "ned2.lex"
{ countChars(); return ','; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 194 "ned2.lex"
{ countChars(); return ':'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 195 "ned2.lex"
{ countChars(); return '='; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 196 "ned2.lex"
{ countChars(); return '('; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 197 "ned2.lex"
{ countChars(); return ')'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 198 "ned2.lex"
{ countChars(); return '['; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 199 "ned2.lex"
{ countChars(); return ']'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 200 "ned2.lex"
{ countChars(); return '{'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 201 "ned2.lex"
{ countChars(); return '}'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 202 "ned2.lex"
{ countChars(); return '.'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 203 "ned2.lex"
{ countChars(); return '?'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 205 "ned2.lex"
{ countChars(); return OR; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 206 "ned2.lex"
{ countChars(); return AND; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 207 "ned2.lex"
{ countChars(); return XOR; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 208 "ned2.lex"
{ countChars(); return NOT; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 210 "ned2.lex"
{ countChars(); return BIN_OR; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 211 "ned2.lex"
{ countChars(); return BIN_AND; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 212 "ned2.lex"
{ countChars(); return BIN_XOR; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 213 "ned2.lex"
{ countChars(); return BIN_COMPL; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 214 "ned2.lex"
{ countChars(); return SHIFT_LEFT; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 215 "ned2.lex"
{ countChars(); return SHIFT_RIGHT; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 217 "ned2.lex"
{ countChars(); return '^'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 218 "ned2.lex"
{ countChars(); return '+'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 219 "ned2.lex"
{ countChars(); return '-'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 220 "ned2.lex"
{ countChars(); return '*'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 221 "ned2.lex"
{ countChars(); return '/'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 222 "ned2.lex"
{ countChars(); return '%'; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 223 "ned2.lex"
{ countChars(); return '<'; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 224 "ned2.lex"
{ countChars(); return '>'; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 226 "ned2.lex"
{ countChars(); return EQ; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 227 "ned2.lex"
{ countChars(); return NE; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 228 "ned2.lex"
{ countChars(); return LE; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 229 "ned2.lex"
{ countChars(); return GE; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 231 "ned2.lex"
{ /* UTF-8 BOM mark, ignore */ }
	YY_BREAK
case 118:
/* rule 118 can match eol */
YY_RULE_SETUP
#line 232 "ned2.lex"
{ countChars(); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 233 "ned2.lex"
{ countChars(); return INVALID_CHAR; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 235 "ned2.lex"
ECHO;
	YY_BREAK
#line 1907 "lex.ned2yy.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(stringliteral):
case YY_STATE_EOF(propertyname):
case YY_STATE_EOF(afterpropertyname):
case YY_STATE_EOF(propertyindex):
case YY_STATE_EOF(propertyvalue):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 341 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 341 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 340);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 235 "ned2.lex"


int yywrap()
{
     return 1;
}

/*
 * - discards all remaining characters of a line of
 *   text from the inputstream.
 * - the characters are read with the input() and
 *   unput() functions.
 * - input() is sometimes called yyinput()...
 */
#ifdef __cplusplus
#define input  yyinput
#endif

/* the following #define is needed for broken flex versions */
#define yytext_ptr yytext

void comment()
{
    int c;
    while ((c = input())!='\n' && c!=0 && c!=EOF);
    if (c=='\n') unput(c);
}

/*
 * - counts the line and column number of the current token in `pos'
 * - yytext[] is the current token passed by (f)lex
 */
static void _count(bool updateprevpos)
{
    int i;

    // printf("DBG: countChars(): prev=%d,%d  pos=%d,%d yytext=>>%s<<\n", prevpos.li, prevpos.co, pos.li, pos.co, yytext);

    if (pos.li==1 && pos.co==0)
        parenDepth = 0;

    if (updateprevpos)
        prevpos = pos;

    for (i = 0; yytext[i] != '\0'; i++) {
        if (yytext[i] == '\n') {
            pos.co = 0;
            pos.li++;
        } else if (yytext[i] == '\t')
            pos.co += 8 - (pos.co % 8);
        else
            pos.co++;
    }

    // printf("count '%s': %d:%d-%d:%d\n", strcmp(yytext,"\n")==0?"\\n":yytext, prevpos.li, prevpos.co, pos.li, pos.co);
    yylloc.first_line   = prevpos.li;
    yylloc.first_column = prevpos.co;
    yylloc.last_line    = pos.li;
    yylloc.last_column  = pos.co;
}

void countChars()
{
    _count(true);
}

void extendCount()
{
    _count(false);
}

int debugPrint(int c)
{
    if (c==CHAR) fprintf(stderr, " ret=CHAR\n");
    else if (c==STRINGCONSTANT) fprintf(stderr, " ret=STRINGCONSTANT\n");
    else if (c>0 && c<=255) fprintf(stderr, " ret='%c'\n", c);
    else fprintf(stderr, " ret=%d\n", c);
    return c;
}

